name: main
on:
 workflow_dispatch:
jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: setup-haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: latest
      - name: run libraries from haxe
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib install flixel-addons
          haxelib install flixel-ui
          haxelib install newgrounds 1.3.0
          haxelib install hscript
          haxelib install hscript-ex
          haxelib install linc_luajit
          haxelib install linc_discord_rpc
          haxelib git polymod https://github.com/swordcube/scriptless-polymod
          haxelib git faxe https://github.com/ashea-code/faxe
      - name: compile
        run: haxelib run lime build windows
      - name: upload
        uses: actions/upload-artifact@main
        with:
          name: windows
          path: export/release/windows/bin
